import { Save, Trash2, Upload, X } from 'lucide-react';
import { useState } from 'react';
import type { CharacterEntity, NpcSheetData } from '../types/rpg.types';
import { CharacterLinkedText, CharacterWikiLinksPanel, type CharacterLinkContext } from './CharacterLinkedText';
import { ImageCropper } from './ImageCropper';

const abilities = [['strength','For'],['dexterity','Des'],['constitution','Con'],['intelligence','Int'],['wisdom','Sab'],['charisma','Car']] as const;
const alignments = ['Leal e Bom','Neutro e Bom','Caótico e Bom','Leal e Neutro','Neutro','Caótico e Neutro','Leal e Mau','Neutro e Mau','Caótico e Mau','Sem alinhamento'];
const input = 'w-full rounded-md border border-[#b99b82] bg-[#fff8e8] px-2.5 py-2 text-sm text-[#351812] placeholder:text-[#8c6b5d] outline-none transition focus:border-[#7b2f25] focus:ring-2 focus:ring-[#8b2d24]/15 disabled:border-transparent disabled:bg-transparent disabled:px-0';
const modifier = (score: number) => Math.floor((score - 10) / 2);

function initial(character: CharacterEntity): NpcSheetData {
  return character.npcSheet ?? { version: 1, secret: '', size: character.size ?? 'Médio', creatureType: character.monsterType ?? 'Humanoide', hitDice: '2d8', savingThrows: {}, passivePerception: 10, challengeRating: character.challengeRating ?? '0', proficiencyBonus: character.proficiencyBonus ?? 2, traits: character.features ?? '', actions: character.actions ?? '', bonusActions: character.bonusActions ?? '', reactions: character.reactions ?? '' };
}

export function NpcCharacterSheet({ character, editing, onEdit, onClose, onDelete, onSave, linkContext, monster = false, villain = false }: { character: CharacterEntity; editing: boolean; onEdit: () => void; onClose: () => void; onDelete: () => void; onSave: (update: Partial<CharacterEntity>) => Promise<void>; linkContext: CharacterLinkContext; monster?: boolean; villain?: boolean; }) {
  const [draft, setDraft] = useState(() => ({ ...character, npcSheet: initial(character) }));
  const sheet = draft.npcSheet!;
  const dexterityModifier = modifier(draft.attributes.dexterity);
  const initiativeAdjustment = sheet.initiativeAdjustment ?? draft.initiative - dexterityModifier;
  const calculatedInitiative = dexterityModifier + initiativeAdjustment;
  const set = (update: Partial<CharacterEntity>) => setDraft((current) => ({ ...current, ...update }));
  const setSheet = (update: Partial<NpcSheetData>) => setDraft((current) => ({ ...current, npcSheet: { ...current.npcSheet!, ...update } }));
  const field = (label: string, value: string | number, change: (value: string) => void, type = 'text') => <label><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-[#7a4036]">{label}</span>{editing || type === 'number' ? <input disabled={!editing} type={type} value={value} onChange={(e) => change(e.target.value)} className={input} /> : <CharacterLinkedText value={String(value)} label={label} context={linkContext} className="border-[#b99b82] bg-[#fff8e8] text-[#351812]" />}</label>;
  const area = (label: string, value: string, change: (value: string) => void, rows = 4) => <label className="block"><span className="mb-1 block border-b border-[#8b2d24] pb-1 font-serif text-lg uppercase tracking-wide text-[#8b2d24]">{label}</span>{editing ? <textarea rows={rows} value={value} onChange={(e) => change(e.target.value)} className={`${input} leading-6`} /> : <CharacterLinkedText value={value} label={label} context={linkContext} className="min-h-24 border-[#b99b82] bg-[#fff8e8] text-[#351812]" />}</label>;

  return <div className={`${villain ? 'villain-sheet' : monster ? 'monster-sheet' : 'npc-sheet'} mx-auto max-w-4xl rounded-lg border-2 border-[#6d5045] bg-[#f5efe3] p-5 text-[#351812] shadow-xl`}>
    <div className="mb-4 flex flex-col gap-4 border-b border-[#8b2d24] pb-4 md:flex-row">
      <div className="group relative h-36 w-36 shrink-0 overflow-hidden rounded border border-[#9b5b4c]/40 bg-[#e8ded0] p-1">{draft.avatar ? <img src={draft.avatar} alt={draft.name} className="h-full w-full object-cover object-center" /> : <span className="grid h-full place-items-center text-xs text-[#8a6a61]">Imagem do NPC</span>}{editing && <ImageCropper circular label="Selecionar e ajustar foto da ficha" onApply={(avatar) => set({ avatar })} className="absolute inset-0 hidden cursor-pointer place-items-center bg-black/50 text-white group-hover:grid"><Upload className="h-5 w-5" /></ImageCropper>}</div>
      <div className="flex-1"><input value={draft.name} onChange={(e) => set({ name: e.target.value })} className="w-full border-b border-[#8b2d24] bg-transparent font-serif text-2xl font-bold uppercase tracking-wide text-[#8b2d24] outline-none" /><div className="mt-3 grid gap-3 sm:grid-cols-2">{field('Tipo de criatura', sheet.creatureType, (v) => setSheet({ creatureType: v }))}{field('Tamanho', sheet.size, (v) => setSheet({ size: v }))}<label><span className="mb-1 block text-[10px] font-bold uppercase text-[#7a4036]">Alinhamento</span><select value={draft.alignment} onChange={(e) => set({ alignment: e.target.value })} className={input}>{alignments.map((item) => <option key={item}>{item}</option>)}</select></label>{!monster && field('Papel', draft.role ?? '', (v) => set({ role: v }))}</div></div>
      <div className="flex gap-2">{editing ? <button onClick={() => onSave(draft)} className="flex h-9 items-center gap-1 rounded bg-[#8b2d24] px-3 text-xs font-bold text-white"><Save className="h-4 w-4" />Salvar</button> : <button onClick={onEdit} className="h-9 rounded bg-[#8b2d24] px-3 text-xs font-bold text-white">Editar</button>}<button onClick={onDelete} className="grid h-9 w-9 place-items-center rounded text-[#8b2d24] hover:bg-[#8b2d24]/10"><Trash2 className="h-4 w-4" /></button><button onClick={onClose} className="grid h-9 w-9 place-items-center rounded text-[#6d5045] hover:bg-black/5"><X className="h-4 w-4" /></button></div>
    </div>
    <div className="mb-4 grid gap-3 border-b border-[#8b2d24] pb-4 sm:grid-cols-2">{field('Ajuste de iniciativa', initiativeAdjustment, (value) => setSheet({ initiativeAdjustment: Number(value) || 0 }), 'number')}<div><span className="mb-1 block text-[10px] font-bold uppercase tracking-wide text-[#7a4036]">Iniciativa calculada</span><output className="block rounded-md border border-[#9b5b4c]/30 px-3 py-2 text-center text-lg font-bold">{calculatedInitiative >= 0 ? '+' : ''}{calculatedInitiative} <small className="font-normal">({10 + calculatedInitiative})</small></output></div></div>
    <div className={`mb-4 grid gap-3 ${monster ? '' : 'md:grid-cols-2'}`}><div className="grid grid-cols-2 gap-x-4 gap-y-1 md:grid-cols-3">{field('CA', draft.ca, (v) => set({ ca: Number(v) }), 'number')}{field('Iniciativa', draft.initiative, (v) => set({ initiative: Number(v) }), 'number')}{field('PV Atual', draft.hp, (v) => set({ hp: Number(v) }), 'number')}{field('PV Máximo', draft.hpMax, (v) => set({ hpMax: Number(v) }), 'number')}{field('Dados de Vida', sheet.hitDice, (v) => setSheet({ hitDice: v }))}{field('Deslocamento', draft.speed, (v) => set({ speed: v }))}</div>{!monster && <div className="grid grid-cols-2 gap-3">{area('Personalidade', draft.personality ?? '', (v) => set({ personality: v }), 3)}{area('Aparência', draft.appearance ?? '', (v) => set({ appearance: v }), 3)}</div>}</div>
    <section className="mb-4 grid grid-cols-2 gap-1 md:grid-cols-3 xl:grid-cols-6">{abilities.map(([key,label]) => { const mod = modifier(draft.attributes[key]); const save = sheet.savingThrows[key] ?? mod; return <div key={key} className="grid grid-cols-[2.2rem_1fr_1fr] items-center bg-[#dfd5c9] px-1 py-1 text-center text-xs"><strong className="text-[#7f352b]">{label}</strong><input type="number" value={draft.attributes[key]} onChange={(e) => set({ attributes: { ...draft.attributes, [key]: Number(e.target.value) } })} className="w-full bg-transparent text-center font-bold outline-none" /><div><span className="block text-[8px] uppercase text-[#805b52]">Mod / SG</span><input aria-label={`Salvaguarda de ${label}`} type="number" value={save} onChange={(e) => setSheet({ savingThrows: { ...sheet.savingThrows, [key]: Number(e.target.value) } })} className="w-full bg-transparent text-center outline-none" /></div><span className="col-start-2 text-[10px] text-[#805b52]">{mod >= 0 ? '+' : ''}{mod}</span></div>; })}</section>
    <div className="mb-4 space-y-2 text-sm"><label className="flex items-center gap-2"><strong>Perícias</strong><input value={draft.skills ?? ''} onChange={(e) => set({ skills: e.target.value })} className={`${input} flex-1`} /></label>{monster && <><label className="flex items-center gap-2"><strong>Vulnerabilidades a Dano</strong><input value={sheet.vulnerabilities ?? ''} onChange={(e) => setSheet({ vulnerabilities: e.target.value })} className={`${input} flex-1`} /></label><label className="flex items-center gap-2"><strong>Resistências a Dano</strong><input value={sheet.damageResistances ?? draft.resistances ?? ''} onChange={(e) => setSheet({ damageResistances: e.target.value })} className={`${input} flex-1`} /></label><label className="flex items-center gap-2"><strong>Imunidades a Dano</strong><input value={sheet.damageImmunities ?? draft.immunities ?? ''} onChange={(e) => setSheet({ damageImmunities: e.target.value })} className={`${input} flex-1`} /></label><label className="flex items-center gap-2"><strong>Imunidades a Condição</strong><input value={sheet.conditionImmunities ?? ''} onChange={(e) => setSheet({ conditionImmunities: e.target.value })} className={`${input} flex-1`} /></label></>}<label className="flex items-center gap-2"><strong>Sentidos</strong><input value={draft.senses ?? ''} onChange={(e) => set({ senses: e.target.value })} className={`${input} flex-1`} /><span className="whitespace-nowrap">Percepção Passiva</span><input type="number" value={sheet.passivePerception} onChange={(e) => setSheet({ passivePerception: Number(e.target.value) })} className="w-16 rounded border border-[#9b5b4c]/30 bg-[#fffaf0] p-2" /></label><label className="flex items-center gap-2"><strong>Idiomas</strong><input value={draft.languages} onChange={(e) => set({ languages: e.target.value })} className={`${input} flex-1`} /></label><div className="flex flex-wrap gap-4"><label className="flex items-center gap-2"><strong>ND</strong><input value={sheet.challengeRating} onChange={(e) => setSheet({ challengeRating: e.target.value })} className="w-20 rounded border border-[#9b5b4c]/30 bg-[#fffaf0] p-2" /></label><label className="flex items-center gap-2"><strong>BP</strong><input type="number" value={sheet.proficiencyBonus} onChange={(e) => setSheet({ proficiencyBonus: Number(e.target.value) })} className="w-20 rounded border border-[#9b5b4c]/30 bg-[#fffaf0] p-2" /></label></div></div>
    <div className="space-y-4">{area('História / Biografia', draft.biography ?? '', (v) => set({ biography: v }), 5)}{!monster && area('Segredo', sheet.secret, (v) => setSheet({ secret: v }))}{monster && area('Resistência Lendária', sheet.legendaryResistance ?? '', (v) => setSheet({ legendaryResistance: v }), 3)}{area('Traços', sheet.traits, (v) => setSheet({ traits: v }), 6)}{area('Ações', sheet.actions, (v) => setSheet({ actions: v }), 7)}{area('Ações Bônus', sheet.bonusActions, (v) => setSheet({ bonusActions: v }))}{area('Reações', sheet.reactions, (v) => setSheet({ reactions: v }))}{monster && area('Ações Lendárias', sheet.legendaryActions ?? '', (v) => setSheet({ legendaryActions: v }), 6)}</div>
    {!editing && <CharacterWikiLinksPanel character={draft} context={linkContext} light />}
  </div>;
}
